server:
  app:
    redis:
      url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379' } %>
      namespace: <%= ENV.fetch('REDIS_NAMESPACE') { 'async_api_with_resque' } %>
application_debug: <%= ENV.fetch('APPLICATION_DEBUG', false) %>
